#!/bin/bash

# Build QT embedded. This can be painful...
# Qt archive: https://download.qt.io/archive/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz
# sudo apt install libudev-dev libinput-dev libxkbcommon-dev
QT_ARCHIVE=qt-everywhere-src-5.15.2.tar.xz
QT_DIR=qt-everywhere-src-5.15.2

if test ! -f "$QT_ARCHIVE"
then
    echo "Qt archive is not present, downloading it now ..."
    wget "https://download.qt.io/archive/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz"
fi

if test ! -f "$QT_DIR"
then
    echo "Qt archive is still packed, extracting it now ..."
    tar -vxf $QT_ARCHIVE
else
    echo "Qt archive is already unpacked, assuming Qt, has already been built"
    echo "exiting"
    exit 0
fi

cd $QTDIR
./configure \
 -prefix ../Qt5 \
 -opensource \
 -confirm-license \
 -skip qtwayland \
 -skip qtlocation \
 -skip qtscript \
 -release \
 -static \
 -no-accessibility \
 -no-cups \
 -verbose \
 -qt-zlib \
 -qt-libpng \
 -no-gif \
 -no-libjpeg \
 -no-openssl \
 -no-iconv \
 -no-dbus \
 -no-opengl \
 -no-glib \
 -nomake examples \
 -libudev \
 -libinput \
 -skip qtdeclarative \
 -skip qtlocation \
 -skip qtmultimedia \
 -skip qtquickcontrols \
 -skip qtsensors \
 -skip qtwebsockets \
 -skip qtwinextras \
 -skip qtwebchannel \
 -skip qtwebengine \
 -skip qttools

make -j8
make install

echo "--------------------------"
echo "- Qt has been installed! -"
echo "--------------------------"
