#!/bin/bash

# Build QT embedded. This can be painful...
# Qt archive: https://download.qt.io/archive/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz
# sudo apt install libudev-dev libinput-dev libxkbcommon-dev

#export QTDIR=`pwd`/`echo "$QT_ARCHIVE" | sed -e 's/.tar.gz//'`
export QTDIR=qt-everywhere-src-5.15.2
cd $QTDIR
#make clean
#make confclean
./configure \
 -prefix ../Qt5 \
 -opensource \
 -confirm-license \
 -skip qtwayland \
 -skip qtlocation \
 -skip qtscript \
 -release \
 -static \
 -no-accessibility \
 -no-cups \
 -verbose \
 -qt-zlib \
 -qt-libpng \
 -no-gif \
 -no-libjpeg \
 -no-openssl \
 -no-iconv \
 -no-dbus \
 -no-opengl \
 -no-glib \
 -nomake examples \
 -libudev \
 -libinput \
 -skip qtdeclarative \
 -skip qtlocation \
 -skip qtmultimedia \
 -skip qtquickcontrols \
 -skip qtsensors \
 -skip qtwebsockets \
 -skip qtwinextras \
 -skip qtwebchannel \
 -skip qtwebengine \
 -skip qttools

make -j8
make install

