#include "linbotextbrowser.h"

LinboTextBrowser::LinboTextBrowser(QWidget* parent) : QTextBrowser(parent)
{
    this->setStyleSheet("QTextBrowser {"
                        "border: 0 0 0 0;"
                        "border-bottom: 1px solid " + gTheme->getColor(LinboGuiTheme::LineColor).name() + ";"
                        "background: " + gTheme->getColor(LinboGuiTheme::ElevatedBackgroundColor).name() + ";"
                        "padding-left: 5px;"
                        "color: " + gTheme->getColor(LinboGuiTheme::TextColor).name() + ";"
                        "}"
                        "QTextBrowser:focus {"
                        "border-bottom: 1px solid " + gTheme->getColor(LinboGuiTheme::AccentColor).name() + ";"
                        "}"
                        "QScrollBar:vertical {"
                        "    background:lightgrey;"
                        "    width:10px;    "
                        "    margin: 0px 0px 0px 0px;"
                        "}"
                        "QScrollBar::handle:vertical {"
                        "    background: grey;"
                        "    min-height: 0px;"
                        "}"
                        "QScrollBar::add-line:vertical {"
                        "    background: grey;"
                        "    height: 0px;"
                        "    subcontrol-position: bottom;"
                        "    subcontrol-origin: margin;"
                        "}"
                        "QScrollBar::sub-line:vertical {"
                        "    background: grey;"
                        "    height: 0 px;"
                        "    subcontrol-position: top;"
                        "    subcontrol-origin: margin;"
                        "}");
}
